### PR TITLE
Bump ember-cli-babel from 6.7.1 to 7.26.10

### PR DESCRIPTION
**Pull request by herzzanu**
Solves https://github.com/ember-intl/cp-validations/issues/74

### CODE REVIEW

**Comment by herzzanu** [comment]
@jasonmit @buschtoens Could you please have a look at this? 🙏  It might help a lot of people trying to upgrade to the latest Ember version.

**Comment by herzzanu** [comment]
Any luck we can get this one merged? 🙏

**Review by buschtoens — APPROVED** [review]

**Comment by buschtoens** [comment]
Sorry that this was left hanging so long. I unfortunatel didn't have a lot of time to spend on open source the past months.

I've never used `@ember-intl/cp-validations` myself, so I'm not really familiar with this project.

- Do you think there's anything in particular I should pay attention to?
- Looking at the [changelog for `ember-cli-babel@7.0.0`](https://github.com/babel/ember-cli-babel/blob/v7.8.0/CHANGELOG.md#v700-2018-08-28) I think this should be a major release. Do you agree?

**Comment by buschtoens** [comment]
@herzzanu This project is somewhat irrecoverably out-of-date. I opted for regenerating it from scratch and copying over and modernizing the few actual source files: #82

Unfortunately, as you're most likely already aware, issues like [qonto/ember-cp-validations#3](https://github.com/qonto/ember-cp-validations/pull/3) or usage of the `Ember` global in `ember-cp-validations` & `ember-validators` are blocking issues.

I'm circumventing these for local development and CI via `patch-package`. This will _not_ work in production use. Users will have to ensure themselves that compatible dependency versions are used.

I would appreciate, if you could publish `@qonto/ember-cp-validations` to npm and also take a look at my PR #82. There are still some more compatibility issues with `ember-cp-validations`, that are not yet in the @qonto repo, and there are issues with `ember-validators`.

**Pull request merged**
