### PR TITLE
chore: re-generate project with latest `ember-cli`

### PR DESCRIPTION
**Pull request by buschtoens**
This project was insanely far out of date. Simply upgrading `ember-cli-babel` (#75) unfortunately doesn't seem to cut it. Furthermore, CI has been broken for ages.

Considering it's small scope, I've opted for re-generating the project from scratch by doing the following:

- delete all files in the repo
- `ember addon --yarn --skip-git --skip-npm @ember-intl/cp-validations`
- move over all new files
- compare diff and restore actual code
- modernize
- patch `ember-cp-validations`
  - based on [`qonto/ember-cp-validations`](https://github.com/qonto/ember-cp-validations)
  - and additional patches
- patch `ember-validator`

Unless `ember-cp-validations` & `ember-validator` are published upstream with those fixes this PR cannot be published for production use.

### CODE REVIEW

**Comment by herzzanu** [comment]
@buschtoens Thanks for the work done to revive this addon :) So basically what we should do now is publish https://github.com/qonto/ember-cp-validations to npm so we can use it here? v4.0.0-beta.13.1 uses the latest version of https://github.com/offirgolan/ember-validators

Let me know if this is what we need as the next step.

**Comment by justinbaltazar** [comment]
Hi @jasonmit @herzzanu @Turbo87, 

Wanted to follow-up on this PR. What work is needed to get this merged with `main`? These changes are needed for this library to be compatible with Ember 4.x. It looks like this PR has been in limbo for a few months now.

cc: @buschtoens

**Comment by jasonmit** [comment]
@justinbaltazar I've been out of the ember community for a while but verified @buschtoens has the proper github & npm permissions to push forward this change.

**Comment by fsmanuel** [comment]
Superseded by https://github.com/ember-intl/cp-validations/pull/87

**Pull request closed without merging**
